# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 100
    ignore:
      # Update homeassistant monthly
      - dependency-name: "homeassistant"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 100
    ignore:
      # Update all other dependencies daily
      - dependency-name: "colorlog"
      - dependency-name: "pip"
      - dependency-name: "ruff"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:10"
      timezone: "America/Toronto"
    open-pull-requests-limit: 100
